### ISSUE TITLE
feature: Detect filetype by default

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [tree-sitter-grammars/tree-sitter-hyprlang#13]
### Did you check the tree-sitter docs?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

In readme we have a suggestion to use

```lua
vim.filetype.add({
  pattern = { [".*/hyprland%.conf"] = "hyprlang" },
})
```

to automate config file detection.

Is there a reason that's not a default?

### Describe the solution you'd like

Include detection by default with the plugin. It's something everyone would need to set up anyway.

### Describe alternatives you've considered

Considering that Hyprland supports multiple config files via [source](https://wiki.hyprland.org/Configuring/Keywords/#sourcing-multi-file), it makes more sense to use

```lua
vim.filetype.add({
    pattern = { [".*/hypr/.*%.conf"] = "hyprlang" },
})

```

**Comment by MahouShoujoMivutilde** [comment]
I haven't noticed it's no longer a neovim plugin. My bad.

**Comment by clason** [comment]
> Is there a reason that's not a default?

Because nobody has bothered to make a PR to vim/vim, which is how default filetype detection happens. This could be you!
