### ISSUE TITLE
bug: Error on , and $variables in variable definition

### ISSUE THREAD

**Issue by xVermillionx** [tree-sitter-grammars/tree-sitter-hyprlang#14]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

The bug lies in defining a variable in Treesitter where placing another variable or just having a comma in a variable definition results in the parser not parsing correctly. 

![Screenshot-2024-03-17--12-29-29](https://github.com/tree-sitter-grammars/tree-sitter-hyprlang/assets/76707179/6f1a9f1e-9efb-4795-90c5-81eafde85822)

### Steps To Reproduce/Bad Parse Tree

1. Add new variable in a hyprland config
2. insert ',' and/or '$somevariable' in its definition

### Expected Behavior/Parse Tree

Expected Behavior for me would be to allow ',' in variables (allow it as part of the variable value) or maybe add `params` to the `_value` for a variable.

### Repro

```hyprland
$notify=notify-send
# $mirror=hyprctl keyword monitor $($notify "Select Mirror" && $select),preferred,auto,1,mirror,$($notify "Select Host" && $select)
$mirror_changed=hyprctl keyword monitor (notify-send "Select Mirror" && test),preferred,auto,1,mirror,(notify-send "Select Host" && test)
$hyprconf=$home/.config
```

**Comment by luckasRanarison** [comment]
Sorry for the late reply because I only saw the issue now. It should be fixed now, thanks for the report!
