### ISSUE TITLE
feature: List to specify the filename that user is sourcing 

### ISSUE THREAD

**Issue by niksingh710** [tree-sitter-grammars/tree-sitter-hyprlang#16]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

No, Not related to a problem

### Describe the solution you'd like

![image](https://github.com/tree-sitter-grammars/tree-sitter-hyprlang/assets/60490474/661419f2-c1de-46ba-ba83-24bbf28a1c35)
The hyprland logo looks nice, but it is not shown in any other file.
e.g if I source my keymaps.conf file from `hypr` dir. or for `hyprlock/hypridle` in general.

**Comment by luckasRanarison** [comment]
It's not related to treesitter grammar, you should check your buffer plugin.
