### ISSUE TITLE
bug: monitor keyword params fails to parse

### ISSUE THREAD

**Issue by seanbreckenridge** [tree-sitter-grammars/tree-sitter-hyprlang#17]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.6

### Describe the bug

Copied from the config here: https://wiki.hyprland.org/Configuring/Monitors/

`monitor=eDP-1, 2256x1504@60, 0x0, auto` does not parse properly

I get a similar error on lines like these:

`bindl=...,switch:off:[switch name],exec,hyprctl keyword monitor "eDP-1, 2560x1600, 0x0, 1"`

### Steps To Reproduce/Bad Parse Tree

![image](https://github.com/tree-sitter-grammars/tree-sitter-hyprlang/assets/7804791/88f9502f-ec36-4c9d-a68e-3c98eb6c8eff)

### Expected Behavior/Parse Tree

params is parsed as strings (or some other type)

### Repro

- `tree-sitter generate`
- `echo 'monitor=eDP-1, 2256x1504@60, 0x0, auto' >conf`
- `tree-sitter parse conf`

```
(configuration [0, 0] - [1, 0]
  (keyword [0, 0] - [1, 0]
    (name [0, 0] - [0, 7])
    (params [0, 8] - [0, 38]
      (string [0, 8] - [0, 13])
      (ERROR [0, 14] - [0, 19])
      (string [0, 19] - [0, 27])
      (ERROR [0, 28] - [0, 31])
      (number [0, 31] - [0, 32])
      (string [0, 33] - [0, 38]))))
```

**Comment by luckasRanarison** [comment]
Sorry for the late reply, it should be fixed now but it may takes some times before the parser and highlights in nvim-treesitter get updated. But as it's a parser issue if think I can close this now.

**Comment by seanbreckenridge** [comment]
Thanks!

I'll look out for the update from `nvim-treesitter` and test when I have a chance

**Comment by luckasRanarison** [comment]
> Thanks!
> 
> I'll look out for the update from `nvim-treesitter` and test when I have a chance

I'll make a PR to nvim-tressitter later
